before_install:
  - openssl aes-256-cbc -K $encrypted_bf733a8f88db_key -iv $encrypted_bf733a8f88db_iv -in deploy_key.enc -out deploy_key -d
  - chmod 600 deploy_key
  - eval `ssh-agent -s` 
  - ssh-add deploy_key
  - git config --global user.name "hs-demo"
  - git config --global user.email "hs-demo@outlook.jp"
  - sudo apt-get -qq update
  - sudo apt-get install -y calibre
  - sudo apt-get install -y xvfb
  - sudo apt-get install -y graphviz
  - sudo apt-get install fonts-ipafont-gothic fonts-ipafont-mincho
language: node_js
node_js:
  - 10 
sudo: true
cache:
  directries:
     - node_modules
script:
  - npm run gitbook build
  - sed -i -E 's/^.*prism-ext.*$//g' book.json
  - xvfb-run gitbook pdf
  - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash ./deploy.sh'

